---
title: "Forecasting Inflation and Interest Rate in Australia"
author: "Yifang"

execute:
  echo: false
  
bibliography: references.bib
---

> **Abstract.** This paper forecastes Australian inflation and interest rate using Bayesian Vector Regressive Model with Stochastic Volatility and a student-t distributed error, with the purpose of allowing time varying volatility and capturing sudden increase in volatility during extreme period such as COVID-19.It is an application of such method, which is suggested as a significant improvement over a standard BVAR, to the Australian macroeconomic variables to generate spot and density forecast using post COVID data.

> **Keywords.** BVARs, Stochastic Volatility, t-distributed error, inflation, interest rate, Australian economy

# Introduction

**Objective:** This paper aims to forecast Australian short term interest rate and inflation. It follows the method in Hartwig(2022), using a BVAR-SV model with its error covariance matrix being student-t distribution.

**Question:** Can the model suggested produce reliable spot and density forecast for Australian inflation and interest rate?

**Motivation:** Volatility variation across time in macroeconomic variables is widely explored in literature(Bloom,2014), which the standard Gaussian error modeling may fail to capture and then leads to unreliable results. Hartwig(2022) suggests that several BVAR models with modified volatility distribution which differentiate from the standard Gaussian perform better under likelihood measurement. The best fitting one with post-COVID19 data is BVAR-t-SV. The stochastic process captures the time persistence of volatility, which is evident in variables such as short term interest rate(Ball and Torous,1999). A student-t distributed error, with relatively fatter tails, can recognize some extreme volatility as temporary spikes instead of persistent effect. The forecast focus on inflation and interest rate due to their strong relevance to policy making and people's daily lives. Many challenges arise post-COVID for government to facilitate the revitalization of the economy, where forecast plays its roles.

# Data

All data is obtained from the RBA. Daily or monthly data is converted to monthly format by averaging. Following Chan(2017, other than cash rate and unemployment, varibles will be transformed using log difference. These are some standard variables to include in a macroeconomics forecast:

**Cash rate:** the cash rate target (series_id:FIRMMCRTD)

**Money aggregate(M1):** the seasonall adjusted M1 money aggregate (series_id:DMAM1S)

**Money aggregate(M3):** the seasonall adjusted M3 money aggregate (series_id:DMAM3S)

**Consumer Price Index** Consumer Price Index (series_id:GCPIAG)

**Real GDP:** Gross Domestic Product in real terms (series_id:GGDPCVGDP)

**Unemployment:** Unemployment rate in percent (series_id:GLFSUPSA)

The data window covers 1990 Q1 to 2023 Q4, as the most up-to-date post-COVID data in Australia, similar to Hartwig(2022). 


```{r read data}
#| echo: false
#| message: false

install.packages("readrba")
library(readrba)

browse_rba_series("aggregate")

un_em = read_rba(series_id = "GLFSUPSA") 
gdp = read_rba(series_id = "GGDPCVGDP")
cpi = read_rba(series_id = "GCPIAG") 

cr = read_rba(series_id = "FIRMMCRTD")

m1 = read_rba(series_id = "DMAM1S") 
m3 = read_rba(series_id = "DMAM3S") 

cpi <- cpi %>% filter(date > as.Date("1989-12-31"))
gdp <- gdp %>% filter(date > as.Date("1989-12-31"))
m1 <- m1 %>% filter(date > as.Date("1989-12-31"))
m3 <- m3 %>% filter(date > as.Date("1989-12-31"))
un_em <- un_em %>% filter(date > as.Date("1989-12-31"))

cpi <- cpi %>% filter(date < as.Date("2024-01-01"))
gdp <- gdp %>% filter(date < as.Date("2024-01-01"))
m1 <- m1 %>% filter(date < as.Date("2024-01-01"))
m3 <- m3 %>% filter(date < as.Date("2024-01-01"))
un_em <- un_em %>% filter(date < as.Date("2024-01-01"))

library(dplyr)
library(lubridate)

m1 <- m1 %>%
  mutate(Quarter = paste(year(date), quarter(date), sep = "Q")) %>%
  group_by(Quarter) %>%
  summarize(Average = mean(value, na.rm = TRUE))

m3 <- m3 %>%
  mutate(Quarter = paste(year(date), quarter(date), sep = "Q")) %>%
  group_by(Quarter) %>%
  summarize(Average = mean(value, na.rm = TRUE))

un_em <- un_em %>%
  mutate(Quarter = paste(year(date), quarter(date), sep = "Q")) %>%
  group_by(Quarter) %>%
  summarize(Average = mean(value, na.rm = TRUE))

cr <- cr %>%
  mutate(Quarter = paste(year(date), quarter(date), sep = "Q")) %>%
  group_by(Quarter) %>%
  summarize(Average = mean(value, na.rm = TRUE))

cr <- cr %>% filter(Quarter != "2024Q1")

```



## Time Series Plot

huh

## ACF and PACF

huh

## Augmented Dickey-Fuller

huh

# Model

Here presents the Bayesian VAR with Stochastic Student-t volatility, the general form of a VAR(p), as in Hartwig(2022):

$$y_t = a_0 +A_1y_{t-1}+...+A_py_{t-p}+ \epsilon_t $$

where $y_t$ is a $n \times 1$ vector and $n$ is the number of variables. $a_0$ is the $n \times 1$ intercept vector. $A_p$ is $n \times n$ coefficient matrix for each lag order $p$. Put it in compact matrix notation:

$$Y = XA+E$$ where $Y_{T \times n}=(y_1', y_2',...,y_T')'$, $X_{T \times K}=(x_1', x_2',...,x_T')'$. Each $x_{K \times 1}=(1, y_{t-1}',...,y_{t-p}')'$. $A$ is a compact coefficient matrix $A_{K \times n}=(a_0', A_1',...,A_p')'$ and $E_{T \times n}=(\epsilon_1', \epsilon_2',...,\epsilon_T')'$. Note, $K = 1+pn$.

References {.unnumbered}
